In [1]:
import gym

In [2]:
env = gym.make('CartPole-v0')
env.reset()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


array([ 0.0411504 ,  0.03675608,  0.01289072, -0.00686823])

In [3]:
print(env.action_space)
print(env.observation_space)

Discrete(2)
Box(4,)


In [4]:
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

env.close()

[ 0.03338737  0.00416976  0.01600217  0.00386398]
[ 0.03347077 -0.19117799  0.01607945  0.30155252]
[ 0.02964721  0.00371114  0.0221105   0.01398378]
[ 0.02972143  0.19850913  0.02239018 -0.27164183]
[ 0.03369162  0.00307496  0.01695734  0.02801811]
[ 0.03375311  0.19794968  0.01751771 -0.25926672]
[ 0.03771211  0.39281723  0.01233237 -0.54637325]
[ 0.04556845  0.58776375  0.00140491 -0.83514518]
[ 0.05732373  0.78286648 -0.015298   -1.12738594]
[ 0.07298106  0.97818548 -0.03784572 -1.4248276 ]
[ 0.09254477  1.17375425 -0.06634227 -1.72909468]
[ 0.11601985  1.36956852 -0.10092416 -2.04166026]
[ 0.14341122  1.17561849 -0.14175737 -1.78183695]
[ 0.16692359  0.98234708 -0.17739411 -1.53637505]
[ 0.18657053  1.17910538 -0.20812161 -1.87876164]
Episode finished after 15 timesteps
[-0.01532389 -0.04577578 -0.01096825 -0.04353453]
[-0.01623941 -0.24073875 -0.01183894  0.24566774]
[-0.02105418 -0.43568963 -0.00692558  0.53459299]
[-0.02976798 -0.63071351  0.00376628  0.82508569]
[-0.04238225 -

[ 0.02925815  0.0035388  -0.01719305 -0.00194778]
[ 0.02932892 -0.19133241 -0.01723201  0.28526133]
[ 0.02550227  0.00403101 -0.01152678 -0.01280625]
[ 0.02558289 -0.19092375 -0.0117829   0.27621766]
[ 0.02176442  0.00436431 -0.00625855 -0.02015818]
[ 0.02185171 -0.19066733 -0.00666171  0.27054355]
[ 0.01803836  0.00454905 -0.00125084 -0.02423305]
[ 0.01812934 -0.19055495 -0.0017355   0.26805496]
[ 0.01431824  0.00459173  0.0036256  -0.02517485]
[ 0.01441008 -0.19058203  0.0031221   0.26864978]
[ 0.01059843 -0.38574839  0.00849509  0.5623158 ]
[ 0.00288347 -0.58098852  0.01974141  0.85766295]
[-0.0087363  -0.386141    0.03689467  0.57125222]
[-0.01645912 -0.58176038  0.04831971  0.87532617]
[-0.02809433 -0.38732741  0.06582624  0.59821759]
[-0.03584088 -0.58330567  0.07779059  0.91088726]
[-0.04750699 -0.38931767  0.09600833  0.64363261]
[-0.05529335 -0.58563733  0.10888099  0.96493905]
[-0.06700609 -0.78204007  0.12817977  1.28974641]
[-0.08264689 -0.97853785  0.15397469  1.61965678]


[-0.02552567  0.62278341  0.00900164 -0.89111114]
[-0.01307     0.81778209 -0.00882059 -1.18095086]
[ 0.00328564  1.01301742 -0.0324396  -1.47638569]
[ 0.02354599  1.20852026 -0.06196732 -1.77902123]
[ 0.04771639  1.01414806 -0.09754774 -1.50622927]
[ 0.06799936  0.82033518 -0.12767233 -1.2455256 ]
[ 0.08440606  0.62706096 -0.15258284 -0.99540766]
[ 0.09694728  0.43427242 -0.17249099 -0.75427012]
[ 0.10563273  0.6312994  -0.1875764  -1.0958861 ]
Episode finished after 20 timesteps
[ 0.02938929 -0.00920576 -0.00791409  0.03080432]
[ 0.02920518 -0.20421333 -0.007298    0.3209798 ]
[ 0.02512091 -0.00898821 -0.00087841  0.02600433]
[ 0.02494115 -0.20409755 -0.00035832  0.31840998]
[ 0.0208592  -0.3992144   0.00600988  0.61097988]
[ 0.01287491 -0.20417696  0.01822948  0.3201959 ]
[ 0.00879137 -0.39955372  0.02463339  0.61857151]
[ 0.00080029 -0.20478436  0.03700482  0.33374759]
[-0.00329539 -0.40041292  0.04367978  0.63786647]
[-0.01130365 -0.2059264   0.0564371   0.35925272]
[-0.01542218 -